# .travis.yml --
#
# Travis CI configuration for Annealing.

#page
#### about branch selection
#
# Travis-CI processes the file ".travis.yml" from the branch containing the git commit that triggers
# the build.  The file ".travis.yml" needs to be  present on all active branches of the project.  It
# is possible to select  which branches to process using a safelist (with  the keyword "only") and a
# blocklist (with the keyword "except"):
#
#    branches:
#      only:
#      - master
#      - stable
#      except:
#      - legacy
#      - /^experimental-.*$/
#
# it is possible  to use regular expressions to  select branch names, by putting  the regexp between
# slash characters.
#
# For details see (URL last verified Dec 21, 2018):
#
#    <https://docs.travis-ci.com/user/customizing-the-build/#building-specific-branches>
#

#page
#### about compiler packages
#
# We select build-by-build  the packages to install;  it should speed up preparation.   By putting a
# single "addons" key at the top level: we would cause all the compilers to be installed for all the
# builds in the matrix; we do not want this.

#page
#### about compiler selection
#
# We select the compiler we want with the  "compiler" key.  This should set the environment variable
# CC to  the associated  compiler executable;  I have  verified that  it actually  does so  when the
# language is C.  I am not sure that it actually does it when the language is C++.
#
# To check which C or C++ compiler is actually selected, we can put the following in every "script:"
# key, before running the "configure" script as follows:
#
#    script: |
#      echo CC=$CC; $CC --version;
#      echo CXX=$CXX; $CXX --version;
#      ./configure
#

#page
#### about dependency packages
#
# We install dependency packages under "/usr/local", so appropriate directories must be added to the
# global path  environment variables, otherwise  the installed packages will  not be found  and used
# correctly by the "configure" script.
#
# Notice  that (as  of May  17, 2018)  Travis CI's  run-time system  raises a  warning if  the first
# directory in the PATH  environment variable is not the one that it  sets.  This causes problems if
# we install the dependencies under the directory "/tmp".
#
# We need the following in the global environment:
#
#   env:
#     global:
#       - PKG_CONFIG_PATH=/usr/local/lib/pkgconfig:/usr/local/share/pkgconfig:$PKG_CONFIG_PATH;
#       - ACLOCAL_PATH=/usr/local/share/aclocal:$ACLOCAL_PATH;
#
# Alternatively, we  can put the  following in every "script:"  key, before running  the "configure"
# script as follows:
#
#   script: |
#     export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig:/usr/local/share/pkgconfig:$PKG_CONFIG_PATH;
#     export ACLOCAL_PATH=/usr/local/share/aclocal:$ACLOCAL_PATH;
#     ./configure
#

#page
#### global configuration

language: c

# We need sudo to install the dependencies under "/usr/local".
#
sudo: true

# Let's just look at the project's dashboard at Travis CI's site.
#
notifications:
  email: false

# We do no git operations, so set the "git clone" depth to the minimum.
#
git:
  depth: 1

# It is possible to select which branches to process.
#
# branches:
#   only:
#     - master

# NOTE  There  must  be only  *one*  env.global  key!!!   Otherwise  the earlier  settings  will  be
# ineffective.
#
# Setting the variable VERBOSE causes "make check" to output the file "test-suite.log".
#
env:
  global:
    - MAKEFLAGS="-j 2"
    - VERBOSE=1
    - LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH;
    - LD_RUN_PATH=/usr/local/lib:$LD_RUN_PATH;
    - PKG_CONFIG_PATH=/usr/local/lib/pkgconfig:/usr/local/share/pkgconfig:$PKG_CONFIG_PATH;
    - ACLOCAL_PATH=/usr/local/share/aclocal:$ACLOCAL_PATH;

#page
#### dependencies management
#

install:
  - ./meta/travis-ci/install-pkg-config.sh;
  - ./meta/travis-ci/install-autoconf.sh;
  - ./meta/travis-ci/install-automake.sh;
  - ./meta/travis-ci/install-texinfo.sh;
  - ./meta/travis-ci/install-gsl.sh;

#page
#### build scripts

before_script:
  # On Linux the GNU  Libtool preparation script is called "libtoolize", while on  OS X it is called
  # "glibtoolize".
  - if test "$TRAVIS_OS_NAME" = osx ; then export LIBTOOLIZE=glibtoolize; else true; fi
  - echo pkg-config --version ; pkg-config --version;
  - echo autoconf --version ; autoconf --version;
  - echo automake --version ; automake --version;
  - sh ./autogen.sh;

matrix:
  fast_finish: true

  include:
    # Plain build under Ubuntu GNU+Linux "trusty", GCC 5.
    - os: linux
      dist: trusty
      compiler: gcc-5
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-5
      script: "./configure --enable-maintainer-mode; make all; make check;"

    # Plain build under Ubuntu GNU+Linux "trusty", GCC 6.
    - os: linux
      dist: trusty
      compiler: gcc-6
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-6
      script: "./configure --enable-maintainer-mode; make all; make check;"

    # Plain build under Ubuntu GNU+Linux "trusty", GCC 7.
    - os: linux
      dist: trusty
      compiler: gcc-7
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-7
      script: "./configure --enable-maintainer-mode; make all; make check;"

    # Plain build under Ubuntu GNU+Linux "trusty", GCC 8.
    - os: linux
      dist: trusty
      compiler: gcc-8
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-8
      script: "./configure --enable-maintainer-mode; make all; make check;"

    # Plain build under Ubuntu GNU+Linux "trusty", CLang automatically selected by Travis CI.
    - os: linux
      dist: trusty
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
      compiler: clang
      script: "./configure --enable-maintainer-mode CFLAGS='-Wno-unknown-attributes'; make all; make check;"

    # Plain build under OS X, XCode 7.3, CLang automatically selected by Travis CI.
    - os: osx
      osx_image: xcode7.3
      compiler: clang
      script: "./configure --enable-maintainer-mode CFLAGS='-Wno-unknown-attributes'; make all; make check;"

    # Plain build under OS X, XCode 8.3, CLang automatically selected by Travis CI.
    - os: osx
      osx_image: xcode8.3
      compiler: clang
      script: "./configure --enable-maintainer-mode CFLAGS='-Wno-unknown-attributes'; make all; make check;"

    # Codecov support under Ubuntu GNU+Linux "trusty", GCC 8.
    - os: linux
      dist: trusty
      compiler: gcc-8
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-8
      script: "./configure --enable-maintainer-mode CFLAGS='-O0 --coverage'; make all; make check;"
      after_success:
        bash <(curl -s https://codecov.io/bash) -xgcov-8

### end of file
